name: flutter_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  authentication_repository:
    path: packages/authentication_repository
  curved_navigation_bar: ^1.0.3
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.1.0
  formz: ^0.4.1
  http: ^0.13.4
  page_transition: ^2.0.9
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/lang/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato2OFL/Lato-Regular.ttf
        - asset: assets/fonts/Lato2OFL/Lato-Bold.ttf
          weight: 700
